default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: web_development
# test:
#   <<: *default
#   database: rails-docker-app_test
# production:
#   <<: *default
#   database: rails-docker-app_production
#   username: rails-docker-app
#   password: <%= ENV["MYSQL_PASSWORD"] %>
#   host: db