default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>

development:
  <<: *default
  database: rails-docker-app_development
test:
  <<: *default
  database: rails-docker-app_test
production:
  <<: *default
  database: rails-docker-app_production
  username: rails-docker-app
  password: <%= ENV["DATABASE_PASSWORD"] %>
